language: java

before_install:
  - chmod +x ./gradlew
install: true

os: linux
dist: trusty
android:
  components:
  - build-tools-29.0.2
  - android-29
jdk:
  - openjdk8

script:
  - ./gradlew build