language: android

before_install:
  - chmod +x ./gradlew
  - yes | sdkmanager "platforms;android-29"
install: true

os: linux
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
jdk:
  - openjdk11

script:
  - ./gradlew build